# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5070dee1e1b8625c567fdf363df206fd7bb81dcb04d4f7acfda20262dee1cd0c6153abd4317b1df52567f3363cfb6f723cee486adaa955af748b59358bd4e068

test:
  secret_key_base: fe21a9243db291cf6566f4a326fe62970740f8c67f54e202bf122e3556078bc9dfffe743fc1ff411be044d60df88e3caf68a986ce37ec6621aaf2bf2350f6f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
